### ISSUE TITLE
[Bug] Set correct damage indicators

### ISSUE THREAD

**Issue by f3cuk** [f3cuk/WICKED-AI#117]
Right now indicators don't work, they always show green even though individual parts are damaged.

**Comment by TBDominator** [comment]
Hey F3cuk, awesome work with these updates!

I have a quick question in relation to this issue you have marked as "Bug". When I hop into my vehicle that spawns from mission file (my own missions), my vehicle has No damage and I get the following Server RPT errors that keep going and don't stop:

21:34:36 "PUBLISH: Attempt B 1-1-B:1 (Troy) REMOTE"
21:34:36 "HIVE: WRITE: "CHILD:308:24:Old_moto_TK_Civ_EP1:0:9360:[349.435,[2872.01,7486.43,0.0393696]]:[[[],[]],[[],[]],[[],[]]]:[["engine",0.271229],["sklo predni P",0.203252],["sklo predni L",0.615053],["karoserie",0.26175],["palivo",0.397361],["Pravy predni tlumic",0.25499],["Pravy zadni tlumic",0.397267]]:0.286502:28720748640349:""
21:34:36 "PUBLISH: Created Old_moto_TK_Civ_EP1 with ID "28720748640349""
21:34:36 "HIVE: WRITE: "CHILD:388:28720748640349:""
21:34:36 "CUSTOM: trying again to get id for: "28720748640349""
21:34:36 "HIVE: WRITE: "CHILD:388:28685748811349:""
21:34:36 "CUSTOM: trying again to get id for: "28685748811349""
21:34:37 "HIVE: WRITE: "CHILD:388:28720748640349:""
21:34:37 "CUSTOM: trying again to get id for: "28720748640349""
21:34:37 "HIVE: WRITE: "CHILD:388:28685748811349:""
21:34:37 "CUSTOM: trying again to get id for: "28685748811349""
21:34:38 "HIVE: WRITE: "CHILD:388:28720748640349:""
21:34:38 "CUSTOM: trying again to get id for: "28720748640349""
21:34:38 "HIVE: WRITE: "CHILD:388:28685748811349:""
21:34:38 "CUSTOM: trying again to get id for: "28685748811349""

Is this related to the bug or is this something totally different?

My Mission file in question can be found with my post below:
http://epochmod.com/forum/index.php?/topic/15671-release-wicked-ai-214-beta-220-out-now/page-86

Any help would be amazing! Thank you

**Comment by f3cuk** [comment]
Yes this is exactly what is happening. The vehicles do get damage, but the indicators won't show it until restart.

**Comment by f3cuk** [comment]
Should be fixed by latest commit
