### ISSUE TITLE
[Recommendation] Move wai_radio_announce to remote/remote.sqf

### ISSUE THREAD

**Issue by Legodev** [f3cuk/WICKED-AI#118]
I would recommend to move the variable wai_radio_announce from config.sqf to remote/remote.sqf.

This makes sure that wai_radio_announce is only enabled if the remote/remote.sqf is included in the mission/init.sqf and then auto enables it. This is possible because wai_radio_announce is a global variable and the game does not care where it got defined.

new remote/remote.sqf:
if (isServer) then {
wai_radio_announce = true;
};
if (!isDedicated) then {
current content of remote/remote.sqf
};

**Comment by f3cuk** [comment]
Will look at this as soon as i get some spare time
