### ISSUE TITLE
error on para drop after mission

### ISSUE THREAD

**Issue by BangL** [f3cuk/WICKED-AI#125]
today i had this in my error log:
it came up while some bandits got para dropped after one of my players cleared an ikea mission.

23:15:34 Error in expression <tion = wai_mission_data select _mission select 3;
};

{
_x setVariable ["Aggress>
23:15:34   Error position: <select 3;
};

{
_x setVariable ["Aggress>
23:15:34   Error select: Type Number, expected Array,Config entry
23:15:34 File z\addons\dayz_server\WAI\compile\bandit_behaviour.sqf, line 14

**Comment by Issty** [comment]
+1 me too. Bandit and Hero para drop missions drop this. :\

**Comment by f3cuk** [comment]
I think this has been fixed for the upcoming version. Please re-open if not.
