### ISSUE TITLE
Vehicle patrols too easy to take out

### ISSUE THREAD

**Issue by Markokil321** [f3cuk/WICKED-AI#130]
The vehicle_patrols are way too easy to take out compared to normal player vehicles.

The AI vehicle armored HMMWV i was able to blow up with 1 DMR mag, whilst a normal armored HMMWV is much harder to take out.

Is there any way we can make the AI vehicle patrol cars harder to blow up?

**Comment by f3cuk** [comment]
Hmm,

Try using different classnames, we didnt change anything to the damage eventhandler. It should be the same as normally, but it might be because vehicles are being used that aren't normally in the game.
