### ISSUE TITLE
Epoch Arma 3 

### ISSUE THREAD

**Issue by nerdalertdk** [f3cuk/WICKED-AI#132]
Use with the a3 version
epoch have there own vests and hats

http://epochmod.com/forum/index.php?/topic/29738-finding-item-ids/

**Comment by nerdalertdk** [comment]
I'm working on E3 now, AI is spawn, still  working on the gear/weapon

bonus, minescript is also working again, including watermines for missions on water

**Comment by nerdalertdk** [comment]
I think is possible to make mission with 10 snappers or 5 sharks if in water, Will test when normal AI is running

**Comment by nerdalertdk** [comment]
Status:
Ai spawn
Can shoot and kill me
Ai loot needs a little work
Crate spawn smokes when get next to it, still need to test at night
Minefield works, still need to test water mines
Remote.sqf need some work
Mission markers work
Position needs work getting a lot of "no position found" before it findes a spot

And I need to read up on a3 new functions

**Comment by f3cuk** [comment]
Nice progress report, I might set up a dev server next weekend or something to start helping you guys out. I need me some coding hehe

**Comment by nerdalertdk** [comment]
don't think I will be able to make a pull request to many changes...

**Comment by nerdalertdk** [comment]
create spawn
AI spawn
Static Guns spawn and works :)
heli patrol spawn / but when reaching finale WP it just cycles around in full speed, trying to fix it.

I mad a lot of rewrite so can't make an pull, will upload in new branch if you make one ?

**Comment by f3cuk** [comment]
Just do a pull request, I'll diffmerge it.

**Comment by nerdalertdk** [comment]
Heli works now slow down to 50 km/h at 50m height, right now I only have the humming bird with two ai on side shooting, still really hard to bring down so I think it's ok balanced 

Other chopper only have mini gun wich is a little op if you ask me

Will try to make a pull in the weekend

Some of the new changes is a ai soldier spawn call hate repeating code ;)
