### ISSUE TITLE
Missing config file in WAI folder

### ISSUE THREAD

**Issue by ReDBaroN1** [f3cuk/WICKED-AI#133]
18:04:12 Warning Message: Script z\addons\dayz_server\WAI\customsettings.sqf not found

Looked in WAI folder and no customsettings.sqf in there.

**Comment by nerdalertdk** [comment]
It's by design

its for your own settings aka. overwrite the default so you don't need to update config after each update.

**Comment by ReDBaroN1** [comment]
ah, ok, sorry for being a pain then... :/

Just that it wrote a line in my server rpt and I wasn't sure if it was an error or not...

I have another which is the file paths for remote message but, I'll check to see if someone else has opened that yet.

Thanks for letting me know. :)
