### ISSUE TITLE
filepath for remote.sqf

### ISSUE THREAD

**Issue by ReDBaroN1** [f3cuk/WICKED-AI#135]
Hi, 

in the instructions the line to add to init is this:
_nil = [] execVM "custom\remote_message\remote_message.sqf";

Just thought  I would point out that this will error unless anyone spots it and changes to:
_nil = [] execVM "custom\remote\remote.sqf";

May be helpful to change either the path in the instructions or the filename and folder in the download. 

Thanks

**Comment by nerdalertdk** [comment]
the remote.sqf should be in your mission

its used to send Radio/chat to players

**Comment by ReDBaroN1** [comment]
I know, it's just if you download it as is, the folder names and the call don't match. It would be more helpful to change one or the other in the download as not everyone checks all the calls when they install.

**Comment by f3cuk** [comment]
Changed. I'll see if i can find some time this weekend to release a final version for A2 :+1:
