### ISSUE TITLE
[REQUEST] Message for mission vehicles not saving to Database

### ISSUE THREAD

**Issue by TBDominator** [f3cuk/WICKED-AI#136]
Hi,

If wai_keep _vehicle = false, is there any way of getting code added to tell players once they hop into a vehicle "vehicle will disappear on server restart" or something along those lines?

**Comment by f3cuk** [comment]
Hey,

Yes this is possible and shouldnt prove too hard to add yourself. Look into the [GetIn](https://community.bistudio.com/wiki/ArmA_2:_Event_Handlers#GetIn) eventhandler on bistudio.com

**Comment by TBDominator** [comment]
Appreciate the reply! Thanks man, I'll look into it

**Comment by f3cuk** [comment]
No worries, if you need any help or if you become stuck, simply reopen this and i will do my best to help you get it done!
