### ISSUE TITLE
Running WAI on a headless client

### ISSUE THREAD

**Issue by h3po** [f3cuk/WICKED-AI#137]
Hi,

I've successfully set up WAI to run on a headless client, with surprisingly few changes necessary.
To do that, I converted the files to a mod folder that can be packed into pbo and signed. Instead of spawning a thread with WAI\init.sqf from the server monitor, I added it to the mission init.sqf like so:

`if (!isDedicated && !hasInterface) then {
    _wai = [] execVM "z\addons\WAI\init.sqf";
};`

I've checked in my changes so far in at https://github.com/h3po/WICKED-AI
There's no pull request yet, as there is a few things that need to be considered before making this a release:
- Users will ask how to setup a hc, and as it is really not that hard (...) we could include installation instructions.
- The BattlEye filters need to be changed so it does not kick/ban the HC for creating units/waypoints/boxes
- Since then all players will be able to spawn such things, we need an alternative solution to prevent it. I have no idea on how to achieve that yet. It may be as simple as adding some secret string to all the spawn code and adding an exlude with that string to the BE filters. It may require additional serverside code.
- The server should have some way of cleaning up existing missions when the HC craps out

With my setup, the server, HC and clients can easily handle missions with AI numbers increased 10-fold without a sweat. The server fps drop minimally (2-3fps) because of the bandwith required, the HC runs fine at 25-40 fps with ~400 AI on the map. The same config without HC on my vanilla Epoch testserver decreases server fps drastically from ~48fps down to 10-20fps.

**Comment by f3cuk** [comment]
Nice work!

Installation instructions would be a big plus yes. When the HC craps out, don't all the created units etc. automatically get wiped? If not, i guess you could check every x seconds if the HC is up and responding and if not just wipe all the stuff it has created. Just add something like _object ``setVariable['hc',true];`` and the do a ``{ if(_x getVariable['hc',false]) then { remove _x; } } count allUnits + allVehicles;``

Impressive numbers, would be great if we could make some more challenging missions without abusing the 50-cals too much.

**Comment by ReDBaroN1** [comment]
I have a massive +1 for this as I love the system but, could only re load it back on my server as an HC as my population, object count and combination of other scripts just couldn't run it. My server would slowly start to take a bath from half way through the restart cycle.

**Comment by h3po** [comment]
@merlijndamman contact me on github, I can't get mail to you because of outlook.com blocklists.

**Comment by emfirstPJX** [comment]
Hello! And at Epoch 1062 will work?

**Comment by h3po** [comment]
I dont' understand your question.

**Comment by emfirstPJX** [comment]
new version released Dayz Epoch 1.0.6.2. works for 1,0,6,2 ?

**Comment by h3po** [comment]
No, it will not work. This issue is from the Arma 2 days...

**Comment by emfirstPJX** [comment]
It's a pity. You can give me this version, you just deleted it, I'll try to adapt it to the new version of A2 EP
