### ISSUE TITLE
WAI breaks traders.

### ISSUE THREAD

**Issue by IT07** [f3cuk/WICKED-AI#138]
WAI 2.2.4 brakes the default and my own custom traders using the overpoch pack from xstreamgaming.
Some traders do not work and some do. This is issue has been tested trough and trough so please take my word for it.

**Comment by f3cuk** [comment]
Wicked AI does not break traders. I simply cannot take your word for it because it is not true, your issue is elsewhere.

**Comment by IT07** [comment]
Then what explains the malfunction of the traders on a default mission and server pbo? (with WAI installed?)

**Comment by IT07** [comment]
I have (again) tested this today and found out that WAI breaks some trader units even with completely default pbo's and no addons or scripts installed except WAI.
And please do not take this personal it is not meant like that. I am just trying to help you and improve the WAI system.

**Comment by nerdalertdk** [comment]
I have no problems with traders on cherno and tavi

**Comment by IT07** [comment]
The traders I am trying are Napf traders. Sorry for not mentioning that earlier.

**Comment by IT07** [comment]
The issue has been fixed! It seems to be related to traders that aren't BLUFOR or CIV.
Note: this issue has only been fixed on my own redesigned traders. Issue is still present in the default Napf traders if WAI is installed on server.
