### ISSUE TITLE
Error at Bunny Ranch Timeout

### ISSUE THREAD

**Issue by Markokil321** [f3cuk/WICKED-AI#141]
Running BETA 2.2.0 V3 - DayZ Epoch Chernarus 1.0.5.1
When the Bunny Ranch mission (edited to my liking) times out, there will be an error in .RPT.

18:32:11 Error in expression <tion = wai_mission_data select _mission select 3;
};

{
_x setVariable ["Aggress>
18:32:11   Error position: <select 3;
};

{
_x setVariable ["Aggress>
18:32:11   Error select: Type Number, expected Array,Config entry
18:32:11 File z\addons\dayz_server\WAI\compile\bandit_behaviour.sqf, line 14

**Comment by Markokil321** [comment]
Apologies, this error was created by me - I added more than one unit to the _dirtyowner group.

**Comment by nerdalertdk** [comment]
Can it run with your modifications?

**Comment by Markokil321** [comment]
Had closed the issue just a second before you commented haha, yeah error was due to my modifications - resolved now!
