### ISSUE TITLE
Missions stop spawning

### ISSUE THREAD

**Issue by StonedReality** [f3cuk/WICKED-AI#145]
I have WAI installed properly, mission system and my static all load and complete ok.  However after about an hour of server up time the missions just stop spawning.  I get no errors at all.   Any ideas?  Thanks

**Comment by Mark44** [comment]
Our RPT will show a mission start. A green circle will appear on the map. The actual mission never starts- I am of the firm belief that Wicked AI is very broken.   Although I can't figure out why.

**Comment by StonedReality** [comment]
After spending some time going through the files it turns out that some of the individual mission files are incorrect.  I manually corrected the code and it works flawlessly.

**Comment by Basti890** [comment]
I had this problem to, the real problem on Chernarus is the spawn radius for mission, it set to 8500 wich is good for large maps liek napf but not for chernarus after lowering the value donw to 6500 all mission spawn awesome. the line should be in the spawn_functions.sqf

in further Version there may shall be a check WHAT World name it is and depending on that the spawn radius (maybe the point also (not always just center?)) depening on which worl with different values. Like its solved in DZMS.
