### ISSUE TITLE
100 Active ground units. But where they are?

### ISSUE THREAD

**Issue by MisterPiBody** [f3cuk/WICKED-AI#156]
Hanging out at Elektro. Sitting at the hill, watching town with binocular - noone was there in 20 minutes. I know, that map is pretty big, but i've no clue how does that stuff work. Are they patroling or just staying still somewhere? Took a ride at some cities, saw nobody. Any advice?

**Comment by f3cuk** [comment]
For help, it's best to visit the Epoch forums at https://epochmod.com/forum/
