### ISSUE TITLE
Hey no matter what i do i can not get the missions to spawn

### ISSUE THREAD

**Issue by hdgzero** [f3cuk/WICKED-AI#158]
http://www.mediafire.com/file/5s33opg4yq3y6fd/server_monitors.sqf
https://www.mediafire.com/file/d4qvz1vtb4k5z76/arma2oaserver.RPT
Ive tried so many things but missions will not spawn in game at all.
Ive runnin normal epoch version 1.0.6.1
ive been trying a bunch of stuff idk if u cant see from the rpt file but yeah
please help me
you can add me on discord ~HDG~#7580
or sometimes people cant find me from that join this server
https://discord.gg/bx6dcXr

**Comment by oiad** [comment]
Can't see a lot from that, WAI isn't even trying to start.
Your deploy anything (deploy bike) is for 1.0.5.1, you need to update it: https://github.com/mudzereli/DayZEpochDeployableBike

``` 9:17:04 Error in expression <LE) exitWith {};
if(isServer) exitWith {dayz_allowedObjects set [count dayz_allo>
 9:17:04   Error position: <dayz_allowedObjects set [count dayz_allo>
 9:17:04   Error Undefined variable in expression: dayz_allowedobjects
 9:17:04 File mpmissions\DayZ_Epoch_11.Chernarus\addons\kits\init.sqf, line 2
```
is also out of date, you need to change any instance of `dayz_allowedobjects` to `DayZ_SafeObjects`

**Comment by hdgzero** [comment]
Could you get on teamviewer of my discord to help me with the wai problem?

**Comment by hdgzero** [comment]
I Fixed the DayZ_SafeObjects problem

**Comment by hdgzero** [comment]
Also wit the bike thing its in the DayZ Epoch Addon Pack

**Comment by hdgzero** [comment]
https://pastebin.com/BR12i5be

**Comment by hdgzero** [comment]
thats me new armaoaserver.rpt i remade the server all new files and only added wai

**Comment by hdgzero** [comment]
https://pastebin.com/GAAX5vPc this is my server_monitor.sqf

**Comment by hdgzero** [comment]
Still would like this help badly
https://cdn.discordapp.com/attachments/359690093549584395/367536715637981194/dayz_server.pbo
that is my dayz_server pbo

**Comment by hdgzero** [comment]
now that i got help getting it work now all my players are spawning at debug

**Comment by hdgzero** [comment]
https://cdn.discordapp.com/attachments/367269461641789440/367642270536826880/dayz_server.pbo
 https://cdn.discordapp.com/attachments/367269461641789440/367643302088015872/arma2oaserver.RPT

getting that on the hive logs
5:00:41 HiveExt(0): [Error] Error executing |CHILD:302:11:false:|
keep spawning in debug

**Comment by Dimens101** [comment]
This was very easy to install for me and worked right away, im running Dayz Vanilla tho but shouldn't matter much, did you also put the WAI folder INSIDE the dayz_server.pbo that is in your @DayZ_Epoch_Server\addons directory? And repack the server_Monitor.sqf file back into the dayz_server.pbo also?

**Comment by f3cuk** [comment]
For help, it's best to visit the Epoch forums at https://epochmod.com/forum/
