### ISSUE TITLE
Not really an Issue just a tip

### ISSUE THREAD

**Issue by justj3ss** [f3cuk/WICKED-AI#163]
With this line:
And add the following line ***below*** it:
	
	```sqf
	"aif_arma1buildings",

IF its the last one on the list it does not need to comma.

**Comment by f3cuk** [comment]
I'd be happy to merge a pull request with code enhancements.

**Comment by worldwidesorrow** [comment]
That entry would never be the last in the list. The instructions say to add it below the first entry. I did that on purpose.
