### ISSUE TITLE
Mission_Example_With_Single_Spawn_Point.sqf

### ISSUE THREAD

**Issue by KrocM** [f3cuk/WICKED-AI#176]
Hi Jason, 

It's no biggie but just wanted to report that I believe there are 2 small errors in the **Mission_Example_With_Single_Spawn_Point.sqf** 

I was trying to copy and paste the code to make my own missions and the server.RPT pointed out a missing comma on line 157
**"The mission timed out and nobody was in the vicinity" <HERE	// mission fail - this message displays when a mission times out.**

And line 108 had this: }; which the RPT flagged.

When I removed the above and added the missing comma the mission worked fine. 

Thanks for your hard work and all you do for us on here, it's greatly appreciated!

**Comment by worldwidesorrow** [comment]
Rogue brace removed. Thanks for reporting the issue!
